#ex3
CREATE TABLE Player(
PId INTEGER PRIMARY KEY,
PName VARCHAR2(20) NOT NULL,
Ranking INTEGER
)

#ex4
CREATE TABLE Tournament(
TId INTEGER PRIMARY KEY,
TName VARCHAR2(30) NOT NULL,
StartDt DATE NOT NULL,
EndDt DATE NOT NULL,
Prize INTEGER NOT NULL
)

#ex5
CREATE TABLE Match(
MId INTEGER ,
TId INTEGER CONSTRAINT match_tid_fk REFERENCES Tournament(TId),
Player1 INTEGER CONSTRAINT match_player1_fk REFERENCES Player(PId),
Player2 INTEGER CONSTRAINT match_player2_fk REFERENCES Player(PId),
MatchDt DATE NOT NULL,
Winner INTEGER CONSTRAINT match_winner_fk REFERENCES Player(PId),
Score VARCHAR2(30) NOT NULL,
CONSTRAINT match_mid_pk PRIMARY KEY(MId,TId),
CONSTRAINT match_player_ck CHECK(Player1<>Player2)
);

#ex6
ALTER TABLE Player ADD (MatchesPlayed INTEGER,MatchesWon INTEGER)

#ex7
