#ex10
INSERT INTO Salesman VALUES(11, 'Elizabeth', 'London')

#ex11
INSERT INTO Product VALUES(110, 'Bat', 50, 'Sports', NULL)

#ex12
SELECT * FROM Product

#ex13
SELECT DISTINCT PRODID , PRICE , CATEGORY FROM Product

#ex14
SELECT DISTINCT CATEGORY FROM Product

#ex15
SELECT PRODID , PDESC , CATEGORY ,DISCOUNT
FROM Product WHERE CATEGORY='Apparel'

#ex16
SELECT PRODID, PDESC , CATEGORY ,DISCOUNT FROM Product WHERE PDESC IS NULL

#ex17
SELECT PRODID, PDESC , CATEGORY ,DISCOUNT FROM Product WHERE CATEGORY='Apparel' AND DISCOUNT>5

#ex18
UPDATE Product SET DISCOUNT=25 WHERE CATEGORY='Sports'

#ex19
UPDATE Product SET PRICE=50 WHERE CATEGORY='Apparel' AND PDESC='Trouser'

#ex20
UPDATE Salesman SET SNAME='Jenny' ,LOCATION='Bristol' WHERE SID=3

#ex21
DELETE FROM SaleDetail WHERE SALEID=1004

#ex22
DELETE FROM SaleDetail WHERE QUANTITY>5

#col16
INSERT INTO Article VALUES( 'A1001' ,'Mouse',500,0,'C')

#Ass17
INSERT INTO Store VALUES('Loyal World','Infy Campus, Mysore','Rohan Kumar');

#ass18
INSERT INTO Bill VALUES(1001,'Loyal World',101,'A1001',1000,'20-OCT-15',2);

#ass19
INSERT INTO Supplier VALUES('S501','Avaya Ltd',9012345678,'Mysore');

#ass20
SELECT DESCR,PRICE FROM Item WHERE DESCR LIKE '%Hard disk'

#ass21
SELECT QUOTATIONID,SNAME,ITEMCODE,QUOTEDPRICE,	QDATE,QSTATUS FROM Quotation 
WHERE QSTATUS='Rejected' OR QSTATUS='Closed'

#ass22
SELECT DESIGNATION,SALARY FROM EMPDETAILS WHERE DESIGNATION='Manager' OR DESIGNATION='Billing Staff'

#ASS23
SELECT roid,location FROM RETAILOUTLET WHERE MANAGERID IS NULL

#ASS24
SELECT orderid, quotationid ,status FROM ORDERS WHERE ORDERDATE>='1-Dec-2014' AND ORDERDATE<='1-Jan-2015'

#ass25
SELECT  ITEMCODE, DESCR , PRICE FROM Item WHERE  CATEGORY='B' AND DESCR LIKE '%Shirt' OR 
DESCR LIKE '% Skirt' AND CATEGORY='B'

#ASS26
SELECT DISTINCT DESIGNATION , SALARY FROM EMPDETAILS 

#ass27
SELECT ITEMCODE,DESCR ,PRICE FROM ITEM 

#ass28
SELECT quotationid, sname FROM quotation WHERE QSTATUS='Accepted' OR QSTATUS='Rejected'

#ASS29
SELECT  itemcode,DESCR, price FROM Item WHERE DESCR LIKE '_r%'

#ASS30
SELECT DISTINCT ITEMTYPE FROM ITEM 

#ASS31
SELECT  orderid, quotationid, status, pymtdate FROM ORDERS WHERE PYMTDATE IS NULL

#ASS32
SELECT DISTINCT ITEMTYPE,CATEGORY FROM ITEM 

#ass33
SELECT EMPID,SALARY AS "Current Salary",SALARY*1.1 AS "New Salary",
SALARY*1.1-SALARY AS "Incremented Amount" FROM EMPDETAILS

#ASS34
INSERT INTO CITY VALUES('Mysore')

#ass35
INSERT INTO ADDRESS VALUES (350, 'Electronics City','Mysore',570018,'Karnataka')

