#ex25
SELECT COUNT(*) as SALE_COUNT FROM SALE WHERE SYSDATE-SLDATE<1800

#COL40
SELECT DISTINCT ITEMTYPE,
CASE WHEN Price BETWEEN 0 AND 499 THEN 'Cheap' 
WHEN Price BETWEEN 500 AND 1999 THEN 'Affordable'
WHEN Price BETWEEN 2000 AND 4999 THEN 'Expensive'
WHEN Price>=5000 THEN 'Very Expensive' 
END AS CLASSIFICATION
FROM ITEM 
ORDER BY ITEMTYPE,CLASSIFICATION ASC

