#ex47
SELECT S.SALEID,S.SLDATE FROM SALESMAN M,SALE S WHERE S.SID=M.SID AND M.LOCATION='London'

#EX48
SELECT M.SID , M.SNAME,M.LOCATION FROM SALESMAN S, SALESMAN M WHERE S.SID<>M.SID AND S.LOCATION=M.LOCATION 

#EX49
SELECT S.SNAME, M.SALEID AS SALEID FROM SALESMAN S LEFT JOIN SALE M ON S.SID=M.SID ORDER BY S.SID

#ex51
SELECT S.SALEID,S.PRODID,M.SID,X.SNAME FROM SALEDETAIL S ,SALE M ,SALESMAN X WHERE S.SALEID=M.SALEID AND M.SID=X.SID

#COL67
SELECT E.ENAME,E.SAL,D.DNAME FROM EMP E,DEPT D WHERE E.SAL>2000 AND D.DEPTNO=E.DEPTNO ORDER BY DNAME

#COL 68
SELECT E.ENAME,D.DNAME FROM EMP E,DEPT D WHERE JOB='MANAGER' AND D.DEPTNO=E.DEPTNO ORDER BY DNAME

#COL69
SELECT DNAME FROM DEPT D WHERE (SELECT COUNT(*) FROM Emp E WHERE E.DEPTNO = D.DEPTNO AND E.SAL > 1500 )> 1


